### ISSUE TITLE
Add ExpressJS

### ISSUE THREAD

**Issue by ominestre** [ominestre/dark-knight#2]
**Description**
Add the base implementation of ExpressJs

**Tasks and Requirements**
- [x] Create MVC server layout
- [x] Add Express server with basic route that just returns a simple message for now
- [x] Setup static resources
