### ISSUE TITLE
Add static file build

### ISSUE THREAD

**Issue by ominestre** [ominestre/dark-knight#5]
**Description**
Create a JS and SCSS build for building static files used in Dark Knight UI

**Tasks and Requirements**
- [x] Use webpack for the JS building
- [x] Webpack must minify files in production mode
- [x] Use nodesass for SCSS building
- [x] Generate sourcemaps for both JS and SCSS
