### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by ominestre** [ominestre/dark-knight#6]
**Description**
A GUI for displaying health metrics for any defined monitors

**Tasks and Requirements**
- [ ] Use a grid layout so that this can be accessed on any device
- [ ] Allow creating of a Health Monitor from within the GUI
- [ ] Allow for updating a Health Monitor from within the GUI
- [ ] Allow a user to signup for email alerting on a health meter
- [ ] Display Health Monitors as a placeholder. Designing the look and feel of a health monitor will come with another feature.

**Comment by ominestre** [comment]
Changed scoping and changes some tasks to be more descriptive.

Dropped all the UI components for updating the actual Health Monitors since those will be part of the Health Monitor UI task, not the overall dashboard.
